server {
    listen 80;
    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate" always;
        add_header Expires "0" always;
        add_header Pragma "no-cache" always;
        index index.html;
        root /usr/share/nginx/html;
        sub_filter '__CLIENT_HOSTNAME__' '$hostname';
        sub_filter_once off;
        try_files $uri $uri/ /index.html;
    }
}
