apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/*.yaml
build:
  artifacts:
    - image: DOCKER_HUB_USERNAME/k3s-cluster-demo_client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "*.js"
    - image: DOCKER_HUB_USERNAME/k3s-cluster-demo_server
      context: server
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "*.html"
          - "*.js"
  local:
    push: true
  tagPolicy:
    sha256: {}
