apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route
spec:
  entryPoints:
    - web
  routes:
    - match: (Host(`k3s`) && PathPrefix(`/api`))
      kind: Rule
      services:
        - name: server
          port: 1337
      middlewares:
        - name: api-stripprefix
    - match: Host(`k3s`)
      kind: Rule
      services:
        - name: client
          port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: api-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /api
